import MDPLib.Probability.Defs

import Mathlib.Algebra.BigOperators.Fin
import Mathlib.Algebra.BigOperators.Group.Finset.Basic
import Mathlib.Data.Fintype.BigOperators

import Mathlib.Data.Fin.Tuple.Sort -- for Equiv.Perm and permutation operations

set_option linter.unusedSectionVars false

variable {R : Type} [Field R] [LinearOrder R] [IsStrictOrderedRing R]
         [CharZero R] [Archimedean R]



/-!
  # Basic properties for probability spaces and expectations

  The main results:
  - expect_comp_eq_sum: The law of the unconscious statistician 
  - The law of total expectations
  - The law of total probabilities
  - Relationship between X < x and X ≤ x for discrete random variables
-/


section General
open Matrix

variable {Ω : Type} [Fintype Ω] {p x : Ω → R}

/-- If a dot product with a nonnegative vector is positive, some coordinate of the
    vector is positive. -/
theorem exists_pos_of_dotProduct_pos (h1 : p ≥ 0) (h : p ⬝ᵥ x > 0) : ∃ ω, x ω > 0 := by
    by_contra! hcon
    have h2 := dotProduct_le_dotProduct_of_nonneg_left hcon h1   
    rw [dotProduct_zero'] at h2
    order 
                          

end General

namespace Findist
open FinRV

variable {Ω : Type} [FinEnum Ω] [Nonempty Ω] {P : Findist R Ω} {B : FinRV Ω Bool}

theorem probability_nonneg : 0 ≤ ℙ[B // P] := 
    by rw [probability_eq_expect_indicator]
       calc 0 = 𝔼[0 //P] := expect_const.symm 
            _ ≤ 𝔼[𝕀 ∘ B//P] := expect_mono indicator_nonneg
       

theorem probability_le_one : ℙ[B // P] ≤ 1 := 
    by rw [probability_eq_expect_indicator]
       calc 𝔼[𝕀 ∘ B//P] ≤ 𝔼[1 // P] := expect_mono indicator_le_one 
            _ = 1 := expect_const 

theorem isProb_probability (P : Findist R Ω) : IsProb ℙ[B // P] := ⟨probability_nonneg, probability_le_one⟩

end Findist


-------- Random variables --------------------------------------------

section RandomVariables
namespace FinRV
open Findist

variable {Ω : Type} [Nonempty Ω] {X Y : FinRV Ω R} {t t₁ t₂ : R}

theorem indicator_leq_mono (h1 : X ≤ Y) (h2: t₁ ≤ t₂) : (𝕀 ∘ (Y ≤ᵣ t₁) : FinRV Ω R) ≤ 𝕀 ∘ (X ≤ᵣ t₂) := by 
    intro ω   
    by_cases h3 : Y ω ≤ t₁
    · simp [FinRV.leq, 𝕀, indicator, h3, (le_trans (le_trans (h1 ω) h3) h2)] 
    · by_cases h5 : X ω ≤ t₂
      repeat simp [h3, h5, 𝕀, indicator] 

theorem indicator_lt_mono (h1 : X ≤ Y) (h2: t₁ ≤ t₂) : (𝕀 ∘ (Y <ᵣ t₁) : FinRV Ω R) ≤ 𝕀 ∘ (X <ᵣ t₂) := by 
    intro ω   
    by_cases h3 : Y ω < t₁
    · have h4 : X ω < t₂ := 
        calc X ω ≤ Y ω := h1 ω
             _ < t₁ := h3
             _ ≤ t₂ := h2 
      simp [FinRV.lt, 𝕀, indicator, h3, h4] 
    · by_cases h5 : X ω < t₂
      repeat simp [h3, h5, 𝕀, indicator] 

theorem gt_of_geq_of_lt {t₁ t₂ : R} (h : t₁ < t₂) (ω) (hω : (X ≥ᵣ t₂) ω ) : (X >ᵣ t₁) ω :=
    by simp [FinRV.gt, FinRV.geq] at hω ⊢
       order

variable [FinEnum Ω] {P : Findist R Ω} {A B : FinRV Ω Bool}

theorem leq_max : (X ≤ᵣ (FinRV.max X)) = 1 :=
    by ext ω; simpa using le_max ω

theorem max_mem_image : (FinRV.max X) ∈ Finset.univ.image X :=
     Finset.max'_mem (Finset.image X Finset.univ) (image_univ_nonempty X)

theorem min_le (ω) : (FinRV.min X) ≤ X ω :=
   Finset.min'_le (Finset.image X Finset.univ) (X ω) (Finset.mem_image_of_mem X (Finset.mem_univ ω))

theorem geq_min : (X ≥ᵣ (FinRV.min X)) = 1 :=
    by ext ω; simpa using min_le ω

-- results for discrete probability distributions
section Atomic 

variable (P : Findist R Ω) (X : FinRV Ω R) (t : R)

theorem _root_.Findist.exists_eq_of_probability_pos {b : R} (h : ℙ[X =ᵣ b // P] > 0) : ∃ω, X ω = b := by 
    obtain ⟨ω, hω⟩ : ∃ω, (𝕀 ∘ (X=ᵣb)) ω > 0 := exists_pos_of_dotProduct_pos (P.nonneg) h 
    use ω
    by_contra!
    simp_all [𝕀, indicator]


/-! Computes the smallest successive potential atom for `t`. It is a potential atom because
    it may have probability zero.
    see also: Finset.exists_next_right -/
@[to_dual] -- autogenerated name: predQuark
def succQuark (t : R) (h : t < (FinRV.max X)) : R := 
     let 𝓧 := Finset.univ.image X
     let 𝓨 := 𝓧.filter (fun x ↦ x > t)
     let h_nonempty : 𝓨.Nonempty := Finset.filter_nonempty_iff.mpr ⟨FinRV.max X, ⟨max_mem_image, h⟩⟩
     𝓨.min' h_nonempty

@[to_dual predQuark_lt]
theorem succQuark_gt {t : R} (h : t < (FinRV.max  X)) : t < (succQuark X t h) := by
    unfold succQuark; extract_lets 𝓧 𝓨 h_nonempty
    exact (Finset.mem_filter.mp (Finset.min'_mem 𝓨 h_nonempty)).right 

@[to_dual predQuark_in_image]
theorem succQuark_in_image {t : R} (h : t < (FinRV.max  X)) : (succQuark X t h) ∈ (Finset.univ.image X) := sorry

theorem exists_leq_eq_lt_of_lt_max (h0 : t < (FinRV.max  X)) : ∃q > t, (X ≤ᵣ t) = (X <ᵣ q) ∧ q ∈ (Finset.univ.image X) := by
     let 𝓧 := Finset.univ.image X
     let 𝓨 := 𝓧.filter (fun x ↦ x > t)
     have hnonempty : 𝓨.Nonempty := Finset.filter_nonempty_iff.mpr ⟨FinRV.max X, ⟨max_mem_image, h0⟩⟩
     let q := 𝓨.min' hnonempty
     have q_ge_t : q > t := (Finset.mem_filter.mp (Finset.min'_mem 𝓨 hnonempty)).right 
     use q
     constructor
     · exact q_ge_t
     · constructor
       · ext ω
         rw [FinRV.leq,FinRV.lt,decide_eq_decide]
         constructor
         · exact fun h2 => lt_of_le_of_lt h2 q_ge_t
         · intro h2
           have hxω : X ω ∉ 𝓨 := by
              by_contra! inY; exact not_lt_of_ge (Finset.min'_le 𝓨 (X ω) inY) h2
           rw [Finset.mem_filter] at hxω
           push Not at hxω
           exact hxω (Finset.mem_image_of_mem X (Finset.mem_univ ω))
       · exact Finset.mem_of_mem_filter q (Finset.min'_mem 𝓨 hnonempty)

theorem exists_leq_eq_lt (P : Findist R Ω) : ∃q > t,  (X ≤ᵣ t) = (X <ᵣ q) :=
       by cases' lt_or_ge t (FinRV.max X) with hlt hge
          · obtain ⟨q, h⟩ := exists_leq_eq_lt_of_lt_max  X t hlt
            exact ⟨q, ⟨h.1, h.2.1⟩⟩
          · have h := le_max (X:=X)
            grw [hge] at h
            let q := t + 1
            have b : ∀ω, X ω < q := fun ω => lt_add_of_le_of_pos (h ω) zero_lt_one
            have ab : (X ≤ᵣ t) = (X <ᵣ q) := by ext ω; simp_all [FinRV.leq, FinRV.lt]
            exact ⟨q, ⟨lt_add_one t, ab⟩⟩

theorem exists_geq_eq_gt_of_min_lt (h0 : t > (FinRV.min X)) : ∃q < t, (X ≥ᵣ t) = (X >ᵣ q) ∧ q ∈ (Finset.univ.image X) := by sorry

end Atomic

section Transformations

-- Monotone transformation of the random variable 

section Monotone
-- TODO: The proofs below are quite repetitive; may be worth it to simplify them

open Function 

variable {f : R → R} {x : R}  

--- LE

omit [FinEnum Ω] in 
theorem leq_le_comp_leq_of_monotone (hm : Monotone f) : (X ≤ᵣ x) ≤ (f ∘ X ≤ᵣ f x) := 
    by intro ω; rw [Bool.le_iff_imp]; simpa using fun a ↦ hm a


omit [FinEnum Ω] in 
theorem leq_le_comp_geq_of_antitone (hm : Antitone f) : (X ≤ᵣ x) ≤ (f ∘ X ≥ᵣ f x) := 
    by intro ω; rw [Bool.le_iff_imp]; simpa using fun a ↦ hm a

omit [FinEnum Ω] in 
theorem leq_eq_comp_leq_of_strictMono (hm : StrictMono f) : (X ≤ᵣ x) = (f ∘ X ≤ᵣ f x) := 
    by ext ω; rw [Bool.eq_iff_iff]; simpa using hm.le_iff_le.symm

omit [FinEnum Ω] in 
theorem leq_eq_comp_geq_of_strictAnti (hm : StrictAnti f) : (X ≤ᵣ x) = (f ∘ X ≥ᵣ f x) := 
    by ext ω; rw [Bool.eq_iff_iff]; simpa using hm.le_iff_ge.symm

--- LT

omit [FinEnum Ω] in 
theorem lt_eq_comp_lt_of_strictMono (hm : StrictMono f) : (X <ᵣ x) = (f ∘ X <ᵣ f x) := 
    by ext ω; rw [Bool.eq_iff_iff]; simpa using hm.lt_iff_lt.symm

omit [FinEnum Ω] in 
theorem lt_eq_comp_gt_of_strictAnti (hm : StrictAnti f) : (X <ᵣ x) = (f ∘ X >ᵣ f x) := 
    by ext ω; rw [Bool.eq_iff_iff]; simpa using hm.lt_iff_gt.symm

--- GE

omit [FinEnum Ω] in 
theorem geq_le_comp_geq_of_monotone (hm : Monotone f) : (X ≥ᵣ x) ≤ (f ∘ X ≥ᵣ f x) := 
    by intro ω; rw [Bool.le_iff_imp]; simpa using fun a ↦ hm a

omit [FinEnum Ω] in 
theorem geq_le_comp_leq_of_antitone (hm : Antitone  f) : (X ≥ᵣ x) ≤ (f ∘ X ≤ᵣ f x) := 
    by intro ω; rw [Bool.le_iff_imp]; simpa using fun a ↦ hm a


omit [FinEnum Ω] in 
theorem geq_eq_comp_geq_of_strictMono (hm : StrictMono f) : (X ≥ᵣ x) = (f ∘ X ≥ᵣ f x) := 
    by ext ω; rw [Bool.eq_iff_iff]; simpa using hm.le_iff_le.symm

omit [FinEnum Ω] in 
theorem geq_eq_comp_leq_of_strictAnti (hm : StrictAnti f) : (X ≥ᵣ x) = (f ∘ X ≤ᵣ f x) := 
    by ext ω; rw [Bool.eq_iff_iff]; simpa using hm.le_iff_ge.symm

--- GT

omit [FinEnum Ω] in 
theorem gt_eq_comp_gt_of_strictMono (hm : StrictMono f) : (X >ᵣ x) = (f ∘ X >ᵣ f x) := 
    by ext ω;  rw [Bool.eq_iff_iff]; simpa using hm.lt_iff_lt.symm


omit [FinEnum Ω] in 
theorem gt_eq_comp_lt_of_strictAnti (hm : StrictAnti f) : (X >ᵣ x) = (f ∘ X <ᵣ f x) := 
    by ext ω; rw [Bool.eq_iff_iff]; simpa using hm.lt_iff_gt.symm


end Monotone

-- TODO: Add similar results for anti-tone functions

section CashInvariance 

variable (c : R) {x : R}

omit [FinEnum Ω] in 
theorem leq_add_const : (X ≤ᵣ x) = (X + c•1 ≤ᵣ x + c) := by ext ω; simp

omit [FinEnum Ω] in 
theorem lt_add_const : (X <ᵣ x) = (X + c•1 <ᵣ x + c) := by ext ω; simp

omit [FinEnum Ω] in 
theorem geq_add_const : (X ≥ᵣ x) = (X + c•1 ≥ᵣ x + c) := by ext ω; simp

omit [FinEnum Ω] in 
theorem gt_add_const : (X >ᵣ x) = (X + c•1 >ᵣ x + c) := by ext ω; simp

end CashInvariance

section Negation 


variable {x : R}

theorem leq_eq_neg_geq_neg : (X ≤ᵣ x) = (-X ≥ᵣ -x) := by ext ω; simp

theorem geq_eq_neg_leq_neg : (X ≥ᵣ x) = (-X ≤ᵣ -x) := by ext ω; simp

theorem lt_eq_neg_gt_neg : (X <ᵣ x) = (-X >ᵣ -x) := by ext ω; simp

theorem gt_eq_neg_lt_neg : (X >ᵣ x) = (-X <ᵣ -x) := by ext ω; simp

end Negation 


end Transformations

end FinRV

end RandomVariables

------------------------------ Probability ---------------------------

section Probability 
namespace Findist
open FinRV

variable {Ω : Type} [FinEnum Ω] [Nonempty Ω] {P : Findist R Ω} {A B C : FinRV Ω Bool} {X Y : FinRV Ω R} {t t₁ t₂ : R}


theorem probability_add_probability_not : ℙ[B // P] + ℙ[¬ᵣB // P] = 1 := 
    by rw [probability_eq_expect_indicator, probability_eq_expect_indicator, ←expect_add, indicator_add_indicator_not_eq_one]
       exact expect_one 

theorem probability_not : ℙ[¬ᵣB // P] = 1 - ℙ[B // P] :=
    by rw [←probability_add_probability_not (P:=P) (B:=B)]; ring 

theorem _root_.FinRV.leq_add_gt : (X ≤ᵣ t) + (X >ᵣ t) = 1 := by
  ext ω
  unfold FinRV.leq FinRV.gt
  simp
  exact le_or_gt (X ω) t

theorem probability_leq_add_probability_gt : ℙ[X ≤ᵣ t // P] + ℙ[X >ᵣ t // P] = 1 := by
  rw [probability_eq_expect_indicator, probability_eq_expect_indicator, ← expect_add]
  have h : (𝕀 ∘ (X ≤ᵣ t)) + (𝕀 ∘ (X >ᵣ t)) = (1 : FinRV Ω R) := by
    ext ω
    unfold FinRV.leq FinRV.gt
    simp [𝕀, indicator]
    by_cases h1 : X ω ≤ t
    · have h2 : ¬ (X ω > t) := not_lt_of_ge h1
      simp [h1, h2]
    · have h3 : X ω > t := lt_of_not_ge h1
      simp [h1, h3]
  rw [h]
  exact expect_one

theorem probability_gt_eq_one_sub : ℙ[X >ᵣ t // P] = 1 -  ℙ[X ≤ᵣ t // P] := by
  rw [←probability_leq_add_probability_gt (P := P) (X := X) (t := t)]
  ring

theorem probability_leq_eq_one_sub :  ℙ[X ≤ᵣ t // P] = 1 - ℙ[X >ᵣ t // P] := by
  rw [←probability_leq_add_probability_gt (P := P) (X := X) (t := t)]
  ring

theorem probability_lt_add_probability_geq : ℙ[X <ᵣ t // P] + ℙ[X ≥ᵣ t // P] = 1 := by
  rw [probability_eq_expect_indicator, probability_eq_expect_indicator, ← expect_add]
  have h : (𝕀 ∘ (X <ᵣ t)) + (𝕀 ∘ (X ≥ᵣ t)) = (1 : FinRV Ω R) := by
    ext ω
    unfold FinRV.lt FinRV.geq
    simp [𝕀, indicator]
    by_cases h1 : X ω < t
    · have h2 : ¬ (X ω ≥ t) := not_le_of_gt h1
      simp [h1, h2]
    · have h3 : X ω ≥ t := le_of_not_gt h1
      simp [h1, h3]
  rw [h]
  exact expect_one

theorem probability_geq_eq_one_sub : ℙ[X ≥ᵣ t // P] = 1 -  ℙ[X <ᵣ t // P] := by
  rw [← probability_lt_add_probability_geq (P := P) (X := X) (t := t)]; ring

theorem probability_lt_eq_one_sub :  ℙ[X <ᵣ t // P] = 1 - ℙ[X ≥ᵣ t // P] := by
  rw [← probability_lt_add_probability_geq (P := P) (X := X) (t := t)]; ring

theorem probability_mono : A ≤ B → ℙ[A // P] ≤ ℙ[B // P] := fun h => expect_mono (indicator_mono h)

theorem probability_leq_mono : X ≤ Y → t₁ ≤ t₂ → ℙ[Y ≤ᵣ t₁ // P] ≤ ℙ[X ≤ᵣ t₂ // P] := by 
  intro hxy ht 
  exact expect_mono (indicator_leq_mono hxy ht)

theorem probability_lt_mono : X ≤ Y → t₁ ≤ t₂ → ℙ[Y <ᵣ t₁ // P] ≤ ℙ[X <ᵣ t₂ // P] := by 
  intro hxy ht
  exact expect_mono (indicator_lt_mono hxy ht)

theorem probability_geq_anti : X ≤ Y → t₁ ≤ t₂ → ℙ[Y ≥ᵣ t₁ // P] ≥ ℙ[X ≥ᵣ t₂ // P] := by 
  intro hxy ht 
  rewrite [probability_geq_eq_one_sub,probability_geq_eq_one_sub] 
  have := probability_lt_mono (P := P) hxy ht 
  linarith 

theorem probability_gt_anti : X ≤ Y → t₁ ≤ t₂ → ℙ[Y >ᵣ t₁ // P] ≥ ℙ[X >ᵣ t₂ // P] := by 
  intro hxy ht 
  rewrite [probability_gt_eq_one_sub,probability_gt_eq_one_sub] 
  have := probability_leq_mono (P := P) hxy ht 
  linarith 

theorem probability_leq_le_probability_lt {q : R} (h : q > t) : ℙ[X <ᵣ q // P] ≥ ℙ[X ≤ᵣ t // P] := by 
     unfold probability 
     apply Finset.sum_le_sum
     intro ω hω
     have h2 : (𝕀 ∘ (X ≤ᵣ t) : FinRV Ω R) ω ≤ (𝕀 ∘ (X <ᵣ q) : FinRV Ω R) ω :=
       by by_cases h3 : X ω ≤ t
          · have h4 : X ω < q := lt_of_le_of_lt h3 h
            simp [FinRV.leq, FinRV.lt, 𝕀, indicator, Function.comp, h3, h4]
          · simp [𝕀, indicator, FinRV.leq, FinRV.lt, Function.comp, h3]
            by_cases h5 : X ω < q <;> simp [h5] 
     exact mul_le_mul_of_nonneg_left h2 (P.nonneg ω)

theorem probability_leq_max : ℙ[X ≤ᵣ (FinRV.max X) // P] = 1 := by rw [leq_max]; exact probability_one P

theorem probability_geq_min : ℙ[X ≥ᵣ (FinRV.min X) // P] = 1 := by rw [geq_min]; exact probability_one P

theorem probability_lt_min : ℙ[X <ᵣ (FinRV.min X) // P] = 0 := by
    rw [probability_lt_eq_one_sub, probability_geq_min]; exact sub_self 1

theorem lt_max_of_probability_leq_lt_one {t : R} (h : ℙ[X ≤ᵣ t // P] < 1) : t < FinRV.max X := by 
       by_contra! hcontra
       have h1 := probability_leq_mono (P := P) (le_refl X) hcontra
       rw [probability_leq_max] at h1
       exact not_le_of_gt h h1

section Rounding ---results for discrete probability distributions

variable (P : Findist R Ω) (X : FinRV Ω R) (t : R)

theorem exists_probability_leq_eq_probability_lt_of_lt_max (h: t < (FinRV.max X)) : 
    ∃q > t, ℙ[X ≤ᵣ t // P] = ℙ[X <ᵣ q // P] ∧ q ∈ (Finset.univ.image X) := sorry
          --let ⟨q, hq⟩ := exists_leq_eq_lt_of_lt_max P t h
          --Exists.intro q ⟨hq.1, ⟨congrArg (probability P) hq.2.1, hq.2.2 ⟩⟩

/-- similar to `exists_probability_leq_eq_probability_lt_of_lt_max` but no precondition -/
theorem exists_probability_leq_eq_probability_lt : ∃q > t,  ℙ[X ≤ᵣ t // P] = ℙ[X <ᵣ q // P] :=
      let ⟨q, hq⟩ := exists_leq_eq_lt X t P
      Exists.intro q ⟨hq.1, congrArg (probability P) hq.2⟩


end Rounding 

section Transformations

section Monotone

-- TODO: The proofs below are quite repetitive; may be worth it to simplify them

open Function 

variable {f : R → R} {x : R}  

--- LE

theorem probability_leq_le_probability_comp_leq_of_monotone (hm : Monotone f) : ℙ[X ≤ᵣ x // P] ≤ ℙ[f ∘ X ≤ᵣ f x // P] := 
   probability_mono (leq_le_comp_leq_of_monotone hm)

theorem probability_leq_eq_probability_comp_leq_of_strictMono (hm : StrictMono f) : ℙ[X ≤ᵣ x // P] = ℙ[f ∘ X ≤ᵣ f x // P] := 
  congrArg (probability P) (leq_eq_comp_leq_of_strictMono hm) 
--- LT

theorem probability_lt_eq_probability_comp_lt_of_strictMono (hm : StrictMono f) : ℙ[X <ᵣ x // P] = ℙ[f ∘ X <ᵣ f x // P] := 
  congrArg (probability P) (lt_eq_comp_lt_of_strictMono hm) 

--- GE

theorem probability_geq_le_probability_comp_geq_of_monotone (hm : Monotone f) : ℙ[X ≥ᵣ x // P] ≤ ℙ[f ∘ X ≥ᵣ f x // P] := 
   probability_mono (geq_le_comp_geq_of_monotone hm)

theorem probability_geq_eq_probability_comp_geq_of_strictMono (hm : StrictMono f) : ℙ[X ≥ᵣ x // P] = ℙ[f ∘ X ≥ᵣ f x // P] := 
  congrArg (probability P) (geq_eq_comp_geq_of_strictMono hm) 

--- GT

theorem probability_gt_eq_probability_comp_gt_of_strictMono (hm : StrictMono f) : ℙ[X >ᵣ x // P] = ℙ[f ∘ X >ᵣ f x // P] := 
  congrArg (probability P) (gt_eq_comp_gt_of_strictMono hm) 

end Monotone 

section CashInvariance 

variable (c : R) {x : R}

theorem probability_leq_add_const : ℙ[X ≤ᵣ x // P] = ℙ[X + c•1 ≤ᵣ x + c // P] := congrArg (probability P) (leq_add_const c)

theorem probability_lt_add_const : ℙ[X <ᵣ x // P] = ℙ[X + c•1 <ᵣ x + c // P] := congrArg (probability P) (lt_add_const c)

theorem probability_geq_add_const : ℙ[X ≥ᵣ x // P] = ℙ[X + c•1 ≥ᵣ x + c // P] := congrArg (probability P) (geq_add_const c)

theorem probability_gt_add_const : ℙ[X >ᵣ x // P] = ℙ[X + c•1 >ᵣ x + c // P] := congrArg (probability P) (gt_add_const c)

end CashInvariance

section Negation 

variable {x : R}

theorem probability_leq_eq_neg_geq_neg :  ℙ[X ≤ᵣ x // P] = ℙ[-X ≥ᵣ -x // P] := by rw [leq_eq_neg_geq_neg]

theorem probability_geq_eq_neg_leq_neg :  ℙ[X ≥ᵣ x // P] = ℙ[-X ≤ᵣ -x // P] := by rw [geq_eq_neg_leq_neg]

theorem probability_lt_eq_neg_gt_neg : ℙ[X <ᵣ x //P] = ℙ[-X >ᵣ -x // P] := by rw [lt_eq_neg_gt_neg]

theorem probability_gt_eq_neg_lt_neg : ℙ[X >ᵣ x //P] = ℙ[-X <ᵣ -x // P] := by rw [gt_eq_neg_lt_neg]

end Negation 

end Transformations

end Findist

end Probability 

------------------------------ CDF ---------------------------

section CDF
namespace Findist
open FinRV

variable {Ω : Type} [FinEnum Ω] [Nonempty Ω] {P : Findist R Ω} {X Y : FinRV Ω R} {t t₁ t₂ : R}

/-- shows CDF is non-decreasing -/
theorem cdf_mono : t₁ ≤ t₂ → cdf P X t₁ ≤ cdf P X t₂ := by
  intro ht; unfold cdf
  apply probability_leq_mono (le_refl X) ht

/-- Shows CDF is monotone in random variable  -/
theorem cdf_anti_of_le : X ≤ Y → cdf P X t ≥ cdf P Y t := by
  intro h; unfold cdf
  apply probability_leq_mono h (le_refl t)

end Findist

end CDF

------------------------------ Expectation ---------------------------

section Expectation 
namespace Findist
open FinRV

variable {Ω : Type} [FinEnum Ω] [Nonempty Ω] {P : Findist R Ω}
variable {k : ℕ} {X : FinRV Ω R} {B : FinRV Ω Bool} {L : FinRV Ω (Fin k)}
variable (g : Fin k → R)

/-- expect_comp_eq_sum: The law of the unconscious statistician (or similar) -/
theorem expect_comp_eq_sum : 𝔼[g ∘ L // P ] = ∑ i, ℙ[L =ᵣ i // P] * (g i) :=
  by rewrite [expect_eq_sum_mul_indicatorEq (X := g ∘ L) (L := L) ]
     apply Fintype.sum_congr
     intro i
     rewrite [←indicator_comp_eq_indicatorEq, ←expectCond_mul_probability (X := g ∘ L) ]
     by_cases! h : ℙ[L =ᵣ i // P] = 0 
     · rw [h];  simp 
     · rw [expectCond_comp i h ]
       ring

theorem expect_expectCondRV : 𝔼[𝔼[X |ᵣ L // P] // P] = 𝔼[X // P] :=
  let g i := 𝔼[X | L =ᵣ i // P]
  calc
    𝔼[𝔼[X |ᵣ L // P] // P ] = ∑ i , ℙ[ L =ᵣ i // P] * 𝔼[ X | L =ᵣ i // P ] := expect_comp_eq_sum g
    _ =  ∑ i , 𝔼[ X | L =ᵣ i // P ] * ℙ[ L =ᵣ i // P] := by apply Fintype.sum_congr; intro i; ring 
    _ =  ∑ i : Fin k, 𝔼[X * (𝕀 ∘ (L =ᵣ i)) // P] := by apply Fintype.sum_congr; exact fun a  ↦ expectCond_mul_probability
    _ =  ∑ i : Fin k, 𝔼[X * (L =ᵢ i) // P] := by apply Fintype.sum_congr; intro i; apply expect_congr; rw[indicator_comp_eq_indicatorEq] 
    _ = 𝔼[X // P]  := by rw [←expect_eq_sum_mul_indicatorEq]


section RV_Unique_Values

variable  {τ:Type} [DecidableEq τ] 

/-- The distinct values of a random variable, as a deduplicated list built from the
    enumeration of the sample space. -/
def _root_.FinRV.imageList (X : FinRV Ω τ) : List τ := List.dedup ((FinEnum.toList Ω).map X)

/-- The image finset of `X` equals the `toFinset` of its `imageList`. -/
theorem _root_.FinRV.image_univ_eq_imageList_toFinset (X : FinRV Ω τ) : Finset.univ.image X = X.imageList.toFinset := by
    ext y
    simp [FinRV.imageList]

theorem _root_.FinRV.sum_image_univ_eq_sum_imageList (f : R → R) :
    (∑ y ∈ (Finset.univ.image X), f y) = ((X.imageList).map f).sum := by
      rw [image_univ_eq_imageList_toFinset]
      exact List.sum_toFinset f (List.nodup_dedup _)


section Generic 

variable {X : FinRV Ω τ}

theorem _root_.FinRV.apply_mem_imageList (ω : Ω) : X ω ∈ X.imageList := by
    simp only [FinRV.imageList, List.mem_dedup, List.mem_map]
    exact ⟨ω, FinEnum.mem_toList ω, rfl⟩

theorem _root_.FinRV.exists_getElem_imageList (ω) : ∃ i : Fin X.imageList.length, X ω = X.imageList[i] := 
  List.exists_mem_iff_get.mp ⟨X ω, ⟨apply_mem_imageList ω, rfl⟩⟩
  
theorem _root_.FinRV.imageList_nodup : X.imageList.Nodup := List.nodup_dedup _

def _root_.MDPLib.List.finIdxOf (L : List τ) (a : τ) (h : a ∈ L) : Fin L.length := 
    ⟨L.idxOf a, List.idxOf_lt_length_of_mem h⟩

@[simp]
theorem _root_.MDPLib.List.getElem_finIdxOf (L : List τ) (a : τ) (h : a ∈ L) : L[MDPLib.List.finIdxOf L a h] = a := 
    List.getElem_idxOf (List.idxOf_lt_length_of_mem h) 

def _root_.FinRV.imageIdxOf (X : FinRV Ω τ) (ω : Ω) : Fin (X.imageList.length) := 
    MDPLib.List.finIdxOf X.imageList (X ω) (apply_mem_imageList ω)

@[simp]
theorem _root_.FinRV.getElem_imageIdxOf (ω : Ω) : X.imageList[X.imageIdxOf ω] = X ω := 
  MDPLib.List.getElem_finIdxOf X.imageList (X ω) (apply_mem_imageList ω)

theorem _root_.FinRV.imageIdxOf_eq_of_eq_getElem {ω i} (h: X ω = X.imageList[i]) : X.imageIdxOf ω = i := by 
  have h1 : X.imageList.Nodup := imageList_nodup 
  rewrite [← getElem_imageIdxOf ω (X := X)] at h 
  exact (List.Nodup.get_inj_iff h1).mp h
  
theorem _root_.FinRV.eq_getElem_iff_imageIdxOf_eq {ω i} : X ω = X.imageList[i] ↔ X.imageIdxOf ω = i := 
  ⟨imageIdxOf_eq_of_eq_getElem, fun h => by rw[←h]; exact Eq.symm (getElem_imageIdxOf ω)⟩


end Generic    

theorem _root_.FinRV.sum_image_univ_eq_sum_fin (f : R → R) : 
    ∑ y ∈ (Finset.univ.image X), f y = ∑ i : Fin X.imageList.length, f (X.imageList[i]) := by 
      rw [sum_image_univ_eq_sum_imageList, ← List.ofFn_getElem_eq_map, List.sum_ofFn]; rfl
      

/-- Shows that our definition of expectation is correct -/ 
theorem expect_eq_sum_probability_mul : 𝔼[ X // P] = ∑ y ∈ (Finset.univ.image X), (ℙ[ X =ᵣ y // P] * y) := by
    -- Reduce to expect_comp_eq_sum: L ω is the index of X ω in X.imageList and g maps an
    -- index back to its value, so that g ∘ L = X.
    let L ω := X.imageIdxOf ω
    have hgL : (fun i => X.imageList[i]) ∘ L = X := funext getElem_imageIdxOf
    conv_lhs => rw [← hgL, expect_comp_eq_sum (P := P) (L := L)]
    rw [sum_image_univ_eq_sum_fin]
    refine Fintype.sum_congr _ _ fun i => ?_
    rw [show (X =ᵣ X.imageList[i]) = (L =ᵣ i) by ext ω; simpa [L, FinRV.eq] using eq_getElem_iff_imageIdxOf_eq]


-- theorem expect_def_correct2 : 𝔼[ X // P] = ∑ y ∈ X.imageList, ℙ[ X =ᵣ y // P] * y := by  sorry
  

end RV_Unique_Values 

end Findist

end Expectation 

section Probability 
namespace Findist
open FinRV

variable {Ω : Type} [FinEnum Ω] [Nonempty Ω] {k : ℕ}  {L : FinRV Ω (Fin k)}
variable {P : Findist R Ω} {B : FinRV Ω Bool}

/-- The law of total probabilities -/
theorem probability_eq_sum : ℙ[B // P] =  ∑ i, ℙ[B * (L =ᵣ i) // P]  := by 
    rewrite [probability_eq_expect_indicator, eq_sum_mul_indicatorEq (𝕀∘B : FinRV Ω R) L, expect_sum]
    apply Fintype.sum_congr
    intro i 
    rewrite [probability_eq_expect_indicator] 
    apply expect_congr
    ext ω
    by_cases h1 : L ω = i 
    repeat by_cases h2 : B ω; repeat simp [h1, h2, 𝕀, indicator ]

end Findist

end Probability 

---- Prababilities and permutations 

section Probability_Permutation
namespace Findist
open FinRV

variable {Ω : Type} [FinEnum Ω] [Nonempty Ω] {P : Findist R Ω} {A B : FinRV Ω Bool} {X Y : FinRV Ω R} {t : R}

def comp (P : Findist R Ω) (σ : Equiv.Perm (Ω)) : Findist R Ω where 
  p :=  P.p ∘ σ
  sum_eq_one := by 
    have h1 : 1 = (1 : Ω → R) ∘ σ := rfl 
    rw [h1, comp_equiv_dotProduct_comp_equiv 1 P.p σ]
    exact P.sum_eq_one
  nonneg := fun ω => P.nonneg (σ ω)

variable (σ : Equiv.Perm (Ω))

theorem expect_comp_perm : 𝔼[X ∘ σ // P.comp σ] = 𝔼[X // P] := by
  unfold expect Findist.comp 
  exact (comp_equiv_dotProduct_comp_equiv P.1 X σ)

theorem probability_comp_perm : ℙ[A ∘ σ // P.comp σ] = ℙ[A // P] := by 
  have h1 : (𝕀 ∘ A ∘ σ : FinRV Ω R) = (𝕀 ∘ A) ∘ σ := by rfl 
  rw [probability_eq_expect_indicator, h1, expect_comp_perm, ←probability_eq_expect_indicator] 
  
theorem _root_.FinRV.leq_comp_perm : (X ∘ σ ≤ᵣ t) = (X ≤ᵣ t) ∘ σ := by unfold FinRV.leq; grind only 

theorem _root_.FinRV.lt_comp_perm : (X ∘ σ <ᵣ t) = (X <ᵣ t) ∘ σ := by unfold FinRV.lt; grind only 

theorem _root_.FinRV.geq_comp_perm : (X ∘ σ ≥ᵣ t) = (X ≥ᵣ t) ∘ σ := by unfold FinRV.geq; grind only 

theorem _root_.FinRV.gt_comp_perm : (X ∘ σ >ᵣ t) = (X >ᵣ t) ∘ σ := by unfold FinRV.gt; grind only 

theorem probability_leq_comp_perm : ℙ[X ∘ σ ≤ᵣ t // P.comp σ] = ℙ[X ≤ᵣ t // P] := by rw [leq_comp_perm, probability_comp_perm]

theorem probability_lt_comp_perm : ℙ[X ∘ σ <ᵣ t // P.comp σ] = ℙ[X <ᵣ t // P] := by rw [lt_comp_perm, probability_comp_perm]

theorem probability_geq_comp_perm : ℙ[X ∘ σ ≥ᵣ t // P.comp σ] = ℙ[X ≥ᵣ t // P] := by rw [geq_comp_perm, probability_comp_perm]

theorem probability_gt_comp_perm : ℙ[X ∘ σ >ᵣ t // P.comp σ] = ℙ[X >ᵣ t // P] := by rw [gt_comp_perm, probability_comp_perm]

end Findist

end Probability_Permutation 
